### ISSUE TITLE
Add Travis build

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/homebrew-rnp#3]
(Edited by @skalee)

- [x] ~Test that formula passes `brew audit`.~ (extracted to #8)
- [ ] Test that stable version is installable from source.
- [ ] Test that HEAD version is installable from source.

**Comment by skalee** [comment]
I don't have write permissions to this repository, but following should work:

```yaml
lang: minimal
os: osx

# Refer to: https://docs.travis-ci.com/user/reference/osx/#macos-version
osx_image:
  - xcode10.2
  - xcode9.4
  - xcode8.3
  - xcode7.3

env:
  global:
    TAP_NAME=riboseinc/rnp
    FORMULA_NAME=${TAP_NAME}/rnp
    OPTS=""

install:
  - brew update
  - brew tap ${TAP_NAME} "${TRAVIS_BUILD_DIR}"
  - brew install ${FORMULA_NAME} ${OPTS}

script:
  - brew test ${FORMULA_NAME}

matrix:
  include:
    - env: OPTS="--HEAD"
```

Possible improvements include running `brew audit`, and building binary packages, which can be uploaded e.g. to Bintray or attached to a GitHub release.
